[opener]
archive = [
  { run = 'ouch compress "$@" "$0.zip"', for = "unix" },
]

edit = [
  { run = '$EDITOR "$@"', block = true },
]

open = [
  { run = 'xdg-open "$@"', orphan = true },
]

mpv = [
  { run = 'mpv "$@"' },
]

pdf = [
  { run = 'firefox "$@"', orphan = true },
]

libreoffice = [
  { run = 'libreoffice "$@"', orphan = true },
]

fallback = [
  { run = 'xdg-open "$@"', orphan = true },
]

[open]
rules = [
  { name = "*/", use = "folder" },
  { mime = "text/html", use = "open" },
  { name = "*.mp4", use = "mpv" },
  { name = "*.avi", use = "mpv" },
  { mime = "video/*", use = "mpv" },
  { name = "*.docx", use = "libreoffice" },
  { mime = "application/pdf", use = "pdf" },
]
